# permissions for end users to view topolvmclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topolvmcluster-viewer-role
rules:
- apiGroups:
  - lvm.openshift.io
  resources:
  - topolvmclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lvm.openshift.io
  resources:
  - topolvmclusters/status
  verbs:
  - get
